[package]
name = "command-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
command-parser = { path = "../command-parser" }
syn = { version = "2", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1"